# helioscope.toml - Configuration (static)
# Replace it with a uuid or similar
# that is node unique. It is used for the
# metrics collection
node_id = "2fd75b6b-cd46-4cae-ba93-30a66ee4fcd4"
metrics_collector_addr = "localhost:8080"
collection_interval_secs = 60

[probes.sysinfo]
cpu = true
memory = true
temperature = true
static_info = true
